/**
 * Resuming, rather than restarting.
 *
 * The engine ran as one all-or-nothing block: a failure on the audience step
 * threw away a completed GitHub ingest and a completed product analysis, and
 * the next attempt paid for both again from zero. Five minutes on "Identifying
 * audience" and the founder is back at the first step with nothing to show.
 *
 * These pin the three things that fixes: a second run reads the repository
 * again only if it has to, a saved product analysis is never regenerated by
 * accident, and the audience step failing does not take the analysis — or the
 * marketing plan, content and schedule after it — down with it.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { createProject, fakeGitHubClient, setupContext, teardown, type TestContext } from './helpers';
import { analyzeRepository } from '@/lib/analysis/analyze';
import { getProvider, setProvider } from '@/lib/ai/client';
import { db } from '@/lib/db/repo';
import type { AiProvider, CompletionRequest } from '@/lib/ai/types';
import type { Project } from '@/lib/types';

/** The deterministic composer, but the audience call fails. */
function providerFailingOn(task: string): AiProvider {
  const real = getProvider();
  return {
    name: real.name,
    live: real.live,
    modelFor: (tier) => real.modelFor(tier),
    complete: async (req: CompletionRequest) => {
      if (req.task === task) throw new Error('provider exploded');
      return real.complete(req);
    },
  };
}

describe('analysis resumes where it stopped', () => {
  let ctx: TestContext;
  let project: Project;

  beforeEach(async () => {
    ctx = await setupContext();
    project = await createProject(ctx.scope, ctx.user.id);
  });

  afterEach(() => teardown());

  it('runs every step the first time', async () => {
    const result = await analyzeRepository(ctx.scope, project, 'acme/taskflow', {
      client: fakeGitHubClient(),
    });

    expect(result.ran).toEqual({ ingest: true, analysis: true, personas: true });
    expect(result.personaError).toBeNull();
    expect(result.personas.length).toBeGreaterThan(0);
  });

  it('does not read the repository or re-analyse it on a second run', async () => {
    const first = await analyzeRepository(ctx.scope, project, 'acme/taskflow', {
      client: fakeGitHubClient(),
    });

    const client = fakeGitHubClient();
    const getRepo = vi.spyOn(client, 'getRepo');

    const second = await analyzeRepository(ctx.scope, project, 'acme/taskflow', { client });

    expect(second.ran).toEqual({ ingest: false, analysis: false, personas: false });
    expect(getRepo).not.toHaveBeenCalled();
    expect(second.analysis.id).toBe(first.analysis.id);
    expect(second.costUsd).toBe(0);
  });

  it('re-reads and replaces everything when a refresh is asked for', async () => {
    await analyzeRepository(ctx.scope, project, 'acme/taskflow', { client: fakeGitHubClient() });

    const refreshed = await analyzeRepository(ctx.scope, project, 'acme/taskflow', {
      client: fakeGitHubClient(),
      refresh: true,
    });

    expect(refreshed.ran).toEqual({ ingest: true, analysis: true, personas: true });
  });

  it('keeps the product analysis when the audience step fails', async () => {
    setProvider(providerFailingOn('analysis.personas'));

    const result = await analyzeRepository(ctx.scope, project, 'acme/taskflow', {
      client: fakeGitHubClient(),
    });

    // The understanding survives, so strategy and content still have a base.
    expect(result.analysis.one_liner.length).toBeGreaterThan(5);
    expect(result.personas).toEqual([]);
    expect(result.personaError).toMatch(/provider exploded/);

    // And the founder is told, without it reading as a dead end.
    const errors = await db().find(ctx.scope, 'automation_errors', {
      where: { project_id: project.id },
    });
    const persona = errors.find((e) => e.scope === 'analysis.personas');
    expect(persona?.fatal).toBe(false);
    expect(persona?.message).toMatch(/Could not identify the audience/);
  });

  it('retries only the audience step after that failure', async () => {
    setProvider(providerFailingOn('analysis.personas'));
    const failed = await analyzeRepository(ctx.scope, project, 'acme/taskflow', {
      client: fakeGitHubClient(),
    });

    setProvider(null);
    const client = fakeGitHubClient();
    const getRepo = vi.spyOn(client, 'getRepo');

    const retry = await analyzeRepository(ctx.scope, project, 'acme/taskflow', { client });

    expect(retry.ran).toEqual({ ingest: false, analysis: false, personas: true });
    expect(getRepo).not.toHaveBeenCalled();
    expect(retry.analysis.id).toBe(failed.analysis.id);
    expect(retry.personas.length).toBeGreaterThan(0);
    expect(retry.personaError).toBeNull();
  });
});

describe('the job that drives it', () => {
  let ctx: TestContext;
  let project: Project;

  beforeEach(async () => {
    ctx = await setupContext();
    project = await createProject(ctx.scope, ctx.user.id);
  });

  afterEach(() => teardown());

  it('does not call a project failed when its analysis survived', async () => {
    const { runJob } = await import('@/lib/jobs/runner');
    const { enqueue } = await import('@/lib/db/repo');

    await analyzeRepository(ctx.scope, project, 'acme/taskflow', { client: fakeGitHubClient() });

    // The ingest is what fails now: no GitHub token in the test environment.
    const job = await enqueue(
      ctx.scope,
      'analyze_repository',
      { projectId: project.id, repository: 'acme/taskflow', refresh: true },
      { projectId: project.id },
    );
    const claimed = await db().get(ctx.scope, 'jobs', job.id);
    await runJob({ ...claimed!, attempts: 1 });

    const after = await db().get(ctx.scope, 'projects', project.id);
    expect(after?.status).toBe('analyzed');
  });
});
