import type { Metadata } from 'next';
import Link from 'next/link';
import { ContactLine, LegalPage, Points, Section } from '@/components/marketing/LegalPage';
import { legalEntity } from '@/lib/legal-contact';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The agreement covering your use of FullSend.',
};

/** Bumped by hand when the text changes, so it never claims to be today's. */
const UPDATED = '27 August 2026';

export default function TermsPage() {
  const operator = legalEntity();

  return (
    <LegalPage
      title="Terms of Service"
      updated={UPDATED}
      intro="FullSend can publish to your social accounts without asking you first. That is the whole point of it, and it is the part of this agreement worth reading carefully."
    >
      <Section heading="1. The agreement">
        <p>
          These terms are between you and <strong>{operator}</strong> (&ldquo;we&rdquo;), and cover
          your use of FullSend. Using the service means you accept them. If you are agreeing on
          behalf of a company, you confirm you are allowed to bind it.
        </p>
      </Section>

      <Section heading="2. What FullSend does">
        <p>
          You connect a GitHub repository and one or more social accounts. FullSend reads the
          repository to understand your product, produces a marketing strategy and content from
          that understanding, schedules it, publishes it to the accounts you connected, reads the
          resulting metrics back, and adjusts what it produces next.
        </p>
      </Section>

      <Section heading="3. Your account">
        <Points>
          <li>You need a valid email address, and you are responsible for what happens under it.</li>
          <li>
            Sign-in is by emailed link. Anyone who can read your email can get into your account, so
            treat it accordingly.
          </li>
          <li>Tell us promptly if you think someone else has access.</li>
        </Points>
      </Section>

      <Section heading="4. Your code and your content">
        <p>
          Your repository and everything in it stays yours. You grant us permission to read and
          process it, and to send derived descriptions of it to the AI provider this deployment is
          configured to use, solely to run the service for you. We claim no ownership of your code
          and no ownership of the content FullSend produces from it — that content is yours to use,
          edit, publish or throw away.
        </p>
        <p>
          You confirm you have the right to connect the repository you connect. Do not point
          FullSend at code you are not entitled to share.
        </p>
      </Section>

      <Section heading="5. Publishing on your behalf">
        <p>
          When you connect an account, you authorise FullSend to post to it. What that means in
          practice depends on the autopilot mode you choose:
        </p>
        <Points>
          <li>
            <strong>Manual</strong> — nothing goes out until you approve each post.
          </li>
          <li>
            <strong>Hybrid</strong> — routine posts go out on schedule; anything promotional waits
            for your approval.
          </li>
          <li>
            <strong>Full Send</strong> — posts go out on schedule without asking you first, within
            the daily cap and quiet hours you set.
          </li>
        </Points>
        <p>
          <strong>
            You remain responsible for everything published to your accounts, including posts
            FullSend published automatically.
          </strong>{' '}
          You can change mode, pause the queue, unschedule an individual post, or disconnect an
          account at any time, and it takes effect immediately for anything not already sent.
        </p>
        <p>
          Your use of Instagram and TikTok through FullSend is also governed by those platforms&rsquo;
          own terms. If a platform suspends or restricts your account, that is between you and them
          — we cannot publish on your behalf without their permission and neither can you.
        </p>
      </Section>

      <Section heading="6. AI-generated content">
        <p>
          The content FullSend produces is generated by a language model. It can be wrong. It can
          claim your product does something it does not. It can produce a phrase that reads badly in
          a context the model knew nothing about. Review before you let it out — and if you run in
          Full Send mode, understand that you are choosing to skip that review.
        </p>
        <p>
          We do not warrant that generated content is accurate, original, or fit to publish, and you
          are responsible for it once it is live.
        </p>
      </Section>

      <Section heading="7. Acceptable use">
        <p>Do not use FullSend to:</p>
        <Points>
          <li>Publish anything unlawful, deceptive, harassing, or infringing someone&rsquo;s rights.</li>
          <li>
            Impersonate a person or organisation, or market a product you have no connection to.
          </li>
          <li>
            Generate spam, or evade the rate limits, review processes or content rules of the
            platforms you connect.
          </li>
          <li>Attack the service — probe it, overload it, or try to reach another user&rsquo;s data.</li>
        </Points>
        <p>We may suspend or close an account that does any of these.</p>
      </Section>

      <Section heading="8. Availability">
        <p>
          FullSend is provided as-is. We do not promise it will be available at any particular time,
          and we do not promise posts will publish at the exact minute they are scheduled — the
          queue depends on infrastructure we do not control, and a post that comes due while the
          scheduler is delayed goes out on the next run rather than on time.
        </p>
        <p>
          Platform APIs change, and permissions get revoked or deprecated. When that breaks
          publishing, FullSend tells you what failed and why rather than failing silently, but it
          cannot promise the platform will keep working the way it does today.
        </p>
      </Section>

      <Section heading="9. Payment">
        <p>
          Where a paid plan applies, fees are billed in advance through Stripe for the period you
          selected and are non-refundable except where the law requires otherwise. You can cancel at
          any time; cancellation takes effect at the end of the period you have paid for. We will
          give notice before changing prices.
        </p>
      </Section>

      <Section heading="10. Ending it">
        <p>
          You can stop using FullSend whenever you like and delete your data — see{' '}
          <Link href="/data-deletion">Delete your data</Link>. We may suspend or terminate an
          account for a breach of section 7, or for non-payment. On termination we stop publishing
          immediately and delete your data as described in the{' '}
          <Link href="/privacy">Privacy Policy</Link>.
        </p>
      </Section>

      <Section heading="11. Liability">
        <p>
          To the extent the law allows, we are not liable for indirect or consequential loss, for
          lost profits, or for damage to your reputation arising from content published through the
          service. Our total liability for any claim is limited to what you paid us in the twelve
          months before it arose. Nothing here limits liability that cannot legally be limited.
        </p>
      </Section>

      <Section heading="12. Changes and contact">
        <p>
          We may update these terms. Material changes will be emailed to account holders before they
          take effect, and the date at the top of this page will change. Continuing to use FullSend
          after that means you accept the new version.
        </p>
        <ContactLine />
      </Section>
    </LegalPage>
  );
}
